### ISSUE TITLE
no tldr pages!

### ISSUE THREAD

**Issue by sethwoodworth** [hidroh/tldroid#22]
I installed tldroid today, and the app doesn't seem to have any tldr-pages. Do I need to force an update?

**Comment by hidroh** [comment]
Looks like there have been some breaking changes to tldr assets hosting. I'll need to check. Thanks for reporting.

**Comment by hidroh** [comment]
Yeah, they changed the JSON schema for `index.json`, replacing object with an array.

**Comment by hidroh** [comment]
Log an issue tldr-pages/tldr#717

**Comment by hidroh** [comment]
@sethwoodworth I published an update to use latest schema. After upgrading, it will automatically refresh local data at the next tldr update (probably few hours to 1 day). Or you can simply uninstall and reinstall the app (version 1.2) to force fetching data.

**Comment by hidroh** [comment]
Well actually it was a mistake from tldr team, they already reverted the change so it should just work again now.

**Comment by sethwoodworth** [comment]
Thank you so much! Works perfectly.  Really beautiful app.

**Comment by philcoffeejunkie** [comment]
Seems like this issue appears again - can't find any tldr pages on my device and the comments in Play Store suggest other users are facing this problem, too

**Comment by lech** [comment]
This is broken again.
