### ISSUE TITLE
Publish on F-Droid

### ISSUE THREAD

**Issue by alexanderadam** [hidroh/tldroid#26]
[You may guess it](https://github.com/hidroh/materialistic/issues/368). :wink: 

I also wasn't able to [find tldroid on F-Droid](https://f-droid.org/repository/browse/?fdfilter=tldroid&fdpage=1&page_id=0).

It would be wonderful if you [could publish them](https://f-droid.org/contribute/#post-1182).

**Comment by hidroh** [comment]
Hi this is just a pet project mainly meant for experiment purpose. I don't plan to publish it to other stores. Thanks for suggesting though.

**Comment by tuxayo** [comment]
@hidroh Can this issue be reopened? While stating that anyone is welcome to help to do the packaging work to get it to F-Droid.
